version: 2


updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      day: tuesday
      interval: weekly
      time: "07:00"
      timezone: Australia/Adelaide
    versioning-strategy: increase-if-necessary
    groups:
      python-prod:
        dependency-type: production
      python-dev:
        dependency-type: development
    labels:
      - dependencies
      - python

  - package-ecosystem: github-actions
    directory: /
    schedule:
      day: tuesday
      interval: weekly
      time: "07:00"
      timezone: Australia/Adelaide
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: npm
    directory: /
    schedule:
      day: tuesday
      interval: weekly
      time: "07:00"
      timezone: Australia/Adelaide
    versioning-strategy: increase-if-necessary
    labels:
      - dependencies
      - nodejs
