baseURL: https://rileychase.net
languageCode: en-au
title: Riley Chase .net
theme: hyde

# Theme configuration
Menus:
  main:
    - Name: GitHub
      URL: https://github.com/Nadock/
    - Name: LinkedIn
      URL: https://www.linkedin.com/in/riley-taylor-chase/
    - Name: Twitter
      URL: https://twitter.com/NadockInTor
    - Name: About
      URL: /about

params:
  # description: Your custom description # TODO: add custom site description for sidebar

