# https://taskfile.dev
version: '3'


dotenv:
  - .env


vars:
  PY_PREFIX:
    sh: if [[ ${PIPENV_ACTIVE:-} != "1" ]]; then echo "pipenv run"; fi


tasks:
  ci:
    desc: Run all tasks required to merge code into the main branch
    cmds:
      - task: ruff:check
      - task: pytest
      - task: mypy
      - task: mdlint
      - task: build
      - task: validate:links
      - task: aws:lint

  ruff:check:
    desc: Check linting and formatting of Python sources with `astral-sh/ruff`.
    cmds:
      - "{{.PY_PREFIX}} ruff check {{.CLI_ARGS}} ."
      - "{{.PY_PREFIX}} ruff format --check {{.CLI_ARGS}} ."

  ruff:fix:
    desc: Fix linting errors in Python sources with `astral-sh/ruff`.
    cmds:
      - "{{.PY_PREFIX}} ruff check --fix {{.CLI_ARGS}} ."
      - "{{.PY_PREFIX}} ruff format {{.CLI_ARGS}} ."

  mypy:
    desc: Run python/mypy Python type checking tool
    cmds:
      - "{{.PY_PREFIX}} mypy {{.CLI_ARGS}} ./site_generator"

  pytest:
    desc: Run unit tests via pytest-dev/pytest
    cmds:
      - "{{.PY_PREFIX}} pytest {{.CLI_ARGS}} ./site_generator"

  mdlint:
    desc: Lint markdown sources with DavidAnson/markdownlint
    cmds:
      - npx markdownlint '**/*.md' {{.CLI_ARGS}} --ignore node_modules --ignore .mypy_cache --ignore .pytest_cache --ignore-path 'pages/debug/markdown.md'

  live:
    desc: Run the site_generator in live rebuild mode
    cmds:
      - "{{.PY_PREFIX}} python -m site_generator live {{.CLI_ARGS}}"

  build:
    desc: Run the site_generator in single build mode
    cmds:
      - "{{.PY_PREFIX}} python -m site_generator build --host rileychase.net {{.CLI_ARGS}}"

  validate:
    desc: Run the inbuilt site_generator validator
    cmds:
      - "{{.PY_PREFIX}} python -m site_generator validate {{.CLI_ARGS}}"

  validate:links:
    desc: Run the inbuilt site_generator validator with dead link detection enabled
    deps:
      - build
    cmds:
      - "{{.PY_PREFIX}} python -m site_generator validate --dead-links --allow-link 'https://www.linkedin.com/.*' --allow-link 'https://zendesk.com' --allow-link 'https://www.canva.com' {{.CLI_ARGS}}"

  emoji:
    desc: Update emoji files
    cmds:
      - ./site_generator/emoji/update.sh

  aws:lint:
    desc: Run cfn-lint across all templates
    cmds:
      - "{{.PY_PREFIX}} pipenv run cfn-lint --include-checks I -- ./aws/**/*.yml"

  aws:website:validate:
    desc: Validate the website_cfn.yml CloudFormation template
    sources:
      - aws/website_cfn.yml
    cmds:
      - aws cloudformation validate-template --template-body file://./aws/website_cfn.yml

  aws:website:deploy:
    desc: Deploy the website_cfn.yml CloudFormation template
    deps:
      - aws:website:validate
    cmds:
      - |
        aws cloudformation deploy --template-file ./aws/website_cfn.yml \
                                  --stack-name website-rileychase-net \
                                  --no-fail-on-empty-changeset \
                                  --tags PROJECT=rileychase.net STAGE=production \
                                  --parameter-overrides \
                                    DomainName=${DOMAIN_NAME} \
                                    CertificateArn=${CERTIFICATE_ARN}

  aws:gh-actions:validate:
    desc: Validate the gha_role_cfn.yml CloudFormation template
    sources:
      - aws/gha_role_cfn.yml
    cmds:
      - aws cloudformation validate-template --template-body file://./aws/gha_role_cfn.yml

  aws:gh-actions:deploy:
    desc: Deploy the gha_role_cfn.yml CloudFormation template
    deps:
      - aws:gh-actions:validate
    cmds:
      - |
        aws cloudformation deploy --template-file ./aws/gha_role_cfn.yml \
                                  --stack-name github-actions-nadock-rileychase-net \
                                  --no-fail-on-empty-changeset \
                                  --capabilities CAPABILITY_IAM \
                                  --tags PROJECT=rileychase.net STAGE=production \
                                  --parameter-overrides \
                                    BucketName=${BUCKET_NAME} \
                                    DistributionID=${DISTRIBUTION_ID} \

  aws:acm:validate:
    desc: Validate the acm_cert_cfn.yml CloudFormation template
    sources:
      - aws/acm_cert_cfn.yml
    cmds:
      - aws cloudformation validate-template --template-body file://./aws/acm_cert_cfn.yml

  aws:acm:deploy:
    desc: Deploy the acm_cert_cfn.yml CloudFormation template
    deps:
      - aws:acm:validate
    cmds:
      - |
        aws --region us-east-1 cloudformation deploy --template-file ./aws/acm_cert_cfn.yml \
                                                     --stack-name website-rileychase-net-cert \
                                                     --no-fail-on-empty-changeset \
                                                     --capabilities CAPABILITY_IAM \
                                                     --tags PROJECT=rileychase.net STAGE=production \
                                                     --parameter-overrides \
                                                       DomainName=${DOMAIN_NAME} \
                                                       HostedZoneId=${HOSTED_ZONE_ID} \
