# https://taskfile.dev

version: '3'


tasks:
  ci:
    cmds:
      - task: black:check
      - task: mypy
      - task: pylint
      - task: pytest
      - task: validate
      - task: mdlint

  black:
    cmds:
      - black site_generator

  black:check:
    cmds:
      - black --check site_generator

  pylint:
    cmds:
      - pylint site_generator

  mypy:
    cmds:
      - mypy site_generator

  pytest:
    cmds:
      - pytest site_generator

  live:
    cmds:
      - python -m site_generator live {{.CLI_ARGS}}

  build:
    cmds:
      - python -m site_generator build {{.CLI_ARGS}}

  validate:
    cmds:
      - python -m site_generator validate {{.CLI_ARGS}}

  mdlint:
    cmds:
      - npx markdownlint '**/*.md' --ignore node_modules --ignore .mypy_cache --ignore .pytest_cache --ignore-path 'pages/markdown_test.md'
