# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com

service: rileychase-net

custom:
  region: ${env:AWS_DEFAULT_REGION , "ap-southeast-2"}
  stage: ${env:STAGE, "dev"}
  resources:
    cloudfront:
      aliases:
        dev:
          - dev.rileychase.net
        prod:
          - www.rileychase.net
          - rileychase.net

provider:
  name: aws
  runtime: python3.7
  stage: ${self:custom.stage}
  region: ${self:custom.region}

resources:
  Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: rileychase.net-${self:custom.stage}
    # CloudFront Distribution for website
    WebsiteCFDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            TargetOriginId:
              Ref: WebsiteBucket
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          DefaultRootObject: index.html
          Enabled: true
          HttpVersion: http2
          Origins:
            - DomainName:
                Fn::Join:
                  - ""
                  - - Ref: WebsiteBucket
                    - ".s3.amazonaws.com"
              Id:
                Ref: WebsiteBucket
              S3OriginConfig:
                OriginAccessIdentity:
                  Fn::Join:
                    - ""
                    - - origin-access-identity/cloudfront/
                      - Ref: DistributionOAI
          PriceClass: PriceClass_All
          Logging:
            Bucket:
              Fn::Join:
                  - ""
                  - - Ref: WebsiteBucket
                    - ".s3.amazonaws.com"
            IncludeCookies: true
            Prefix: cf-logs
          Aliases: ${self:custom.resources.cloudfront.aliases.${self:custom.stage}}
          ViewerCertificate:
            AcmCertificateArn: arn:aws:acm:us-east-1:065006121675:certificate/e9584a1c-07d9-4e64-92a7-0fcdc6b76056
            SslSupportMethod: sni-only
    # Access configuration so the CF Distribution can access the content in S3
    DistributionOAI:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: rileychase.net
    DistributionOAIBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: WebsiteBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                CanonicalUser:
                  Fn::GetAtt:
                    - DistributionOAI
                    - S3CanonicalUserId
              Action:
                - s3:GetObject
              Resource:
                Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - Ref: WebsiteBucket
                    - /*
  Outputs:
    WebsiteBucketOutput:
      Description: The name of the S3 bucket the website will be deployed into.
      Value:
        Ref: WebsiteBucket
