# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com

service: rileychase-net

custom:
  region: ${env:AWS_DEFAULT_REGION , "ap-southeast-2"}
  stage: ${env:STAGE, "dev"}
  output:
    file: .build/stack.json

provider:
  name: aws
  runtime: python3.7
  stage: ${self:custom.stage}
  region: ${self:custom.region}

resources:
  Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: rileychase.net-${self:custom.stage}
  Outputs:
    WebsiteBucketOutput:
      Description: The name of the S3 bucket the website will be deployed into.
      Value:
        Ref: WebsiteBucket
