# Build config for CircleCI

version: 2.1

executors:
  deployment_executor:
    docker:
      - image: docker.io/nadock/rileychase.net-deploy:latest

jobs:
  test:
    executor: deployment_executor
    steps:
      - checkout
      - run:
          name: Running unit tests
          command: |
            cd infra
            make test
  deploy_prod:
    executor: deployment_executor
    steps:
      - checkout
      - deploy:
          name: Deploying prod environment
          environment:
            STAGE: prod
          command: |
            cd infra
            make deploy

workflows:
  version: 2.1
  test_deploy:
    jobs:
      - test
      - deploy_prod:
          requires:
            - test
          filters:
            branches:
              only: master
