#!/usr/bin/env python
"""
Generator script that generates ./site_generator/emoji.py from a gemoji source JSON
file.
"""

import json
import pathlib
import sys

import black


def main() -> None:
    if len(sys.argv) != 3:
        print(
            "usage: emoji_py_gen.py [gemoji_json_path] [output_path]",
            file=sys.stderr,
        )
        sys.exit(1)

    src = pathlib.Path(sys.argv[1])
    dest = pathlib.Path(sys.argv[2])

    # Example emoji_db element
    # {
    #     "emoji": "😀",
    #     "description": "grinning face",
    #     "category": "Smileys & Emotion",
    #     "aliases": ["grinning"],
    #     "tags": ["smile", "happy"],
    #     "unicode_version": "6.1",
    #     "ios_version": "6.0",
    # },
    emoji_db = json.loads(src.read_text("utf-8"))

    lines = [
        '"""This file is autogenerated, DO NOT EDIT."""',
        "",
        "EMOJI = {",
    ]

    for emoji_record in emoji_db:
        for alias in emoji_record["aliases"]:
            lines.append(f'    "{alias}": "{emoji_record["emoji"]}",')

    lines.append("}")

    dest.write_text(black.format_str("\n".join(lines), mode=black.Mode()), "utf-8")


if __name__ == "__main__":
    main()
