import pathlib

import pydantic

from weaving import logging

LOGGER = logging.getLogger()


class SiteGeneratorError(Exception):
    """Base exception class for any `site_generator` errors."""


class PipelineError(SiteGeneratorError):
    """Pipeline failure for a specific source file."""


class ValidationError(pydantic.BaseModel):
    """Site validation errors generated by the `validate` CLI command."""

    error: str
    """A description of the error."""
    file: pathlib.Path
    """The path to the file that contains the validation error."""
    line: int | None = None
    """The line in the file at which the validation error begins, if available."""
    char: int | None = None
    """The character in the line at which the validation error begins, if available."""


def log_error(ex: Exception) -> None:
    """Log an exception according to what kind of exception it is."""
    if isinstance(ex, SiteGeneratorError):
        LOGGER.error(ex)
        LOGGER.debug(ex, exc_info=True)
        return

    LOGGER.error(ex, exc_info=True)
    raise ex
