#!/usr/bin/env python
"""
Generator script that generates ./site_generator/emoji.py from a gemoji source JSON
file.
"""

import json
import pathlib
import sys

import black


def main():  # pylint: disable=missing-function-docstring
    if len(sys.argv) != 3:
        print(
            "usage: emoji_py_gen.py [gemoji_json_path] [output_path]",
            file=sys.stderr,
        )
        sys.exit(1)

    src = pathlib.Path(sys.argv[1])
    dest = pathlib.Path(sys.argv[2])

    # Example emoji_db element
    # {
    #     "emoji": "😀",
    #     "description": "grinning face",
    #     "category": "Smileys & Emotion",
    #     "aliases": ["grinning"],
    #     "tags": ["smile", "happy"],
    #     "unicode_version": "6.1",
    #     "ios_version": "6.0",
    # },
    emoji_db = json.loads(src.read_text("utf-8"))

    lines = [
        '"""This file is autogenerated, DO NOT EDIT."""',
        "# pylint: disable=unused-argument, too-many-lines, too-many-arguments, invalid-name",
        "",
        "emoji = {",
    ]

    for emoji_record in emoji_db:
        for alias in emoji_record["aliases"]:
            lines.append(f'    "{alias}": "{emoji_record["emoji"]}",')

    lines.append("}")
    lines.append("")
    lines.append("")

    lines.append("def to_unicode_emoji(")
    lines.append("    index: str,")
    lines.append("    shortname: str,")
    lines.append("    alias: str,")
    lines.append("    uc: str,")
    lines.append("    alt: str,")
    lines.append("    title: str,")
    lines.append("    category: str,")
    lines.append("    options: dict,")
    lines.append("    md,")
    lines.append("):")
    lines.append('    """Convert markdown emoji marker to Unicode emoji character."""')
    lines.append('    shortname = shortname.removeprefix(":")')
    lines.append('    shortname = shortname.removesuffix(":")')
    lines.append("    return emoji[shortname]")
    lines.append("")
    lines.append("")

    lines.append("def unicode(options, md):")
    lines.append('    """Return the Unicode emoji DB for markdown conversion."""')
    lines.append("    return {")
    lines.append('        "name": "unicode",')
    lines.append('        "emoji": {')
    lines.append('            f":{k}:": {')
    lines.append('                "category": "",')
    lines.append('                "name": k,')
    lines.append('                "unicode": "0",')
    lines.append("            }")
    lines.append("            for k, v in emoji.items()")
    lines.append("        },")
    lines.append('        "aliases": {},')
    lines.append("    }")
    lines.append("")

    dest.write_text(black.format_str("\n".join(lines), mode=black.Mode()), "utf-8")


if __name__ == "__main__":
    main()
