name: Deploy website from PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited

jobs:
  markdown-lint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkou@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install markdown lint
        run: npm install --global markdownlint-cli

      - name: Lint markdown files
        run: markdownlint $(find . -name "*.md" -not -path "themes/*")

  deploy-pr-content:
    name: Deploy PR content
    runs-on: ubuntu-latest
    needs:
      - markdown-lint
    steps:
      - name: Checkout source
        uses: actions/checkou@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Configure deployment variables
        runs: >-
          # GITHUB_REF has the following format: "refs/pull/{pr_number}/merge", we use that to make
          # a CFN compatible prefix with the format "pull-{pr_number}"
          #                                 remove "refs/"      remove "/merge"      swap "/" to "-"
          export PREFIX=$(echo $GITHUB_REF | sed "s/refs\///g" | sed "s/\/merge//g" | sed "s/\//-/g")
          export STAGE=dev
          export AWS_DEFAULT_REGION=ap-southeast-2
          export ACM_CERT_ARN=${{ secrets.DEV_ACM_CERT_ARN }}
