name: Pull Request Checks

on:
  pull_request: {}

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Tooling installs
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup go-task/task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      # Dependency installs
      - name: Install Python dependencies
        run: |
          pip install pipenv
          pipenv install --dev
          echo "$(pipenv --venv)/bin" >> $GITHUB_PATH
          echo "PIPENV_ACTIVE=1" >> $GITHUB_ENV

      - name: Install Node dependencies
        run: npm install

      - name: PR Checks
        run: |
          task --output group \
               --output-group-begin "::group::{{.TASK}}{{if .NAME}}:{{.NAME}}{{end}}" \
               --output-group-end "::endgroup::" \
               ci

  # Temporaroly run cfn-lint seperately while it is incompatiable with Pydantic v2
  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: pip install cfn-lint==v0.78.2

      - name: cfn-lint
        run: cfn-lint --include-checks I -- ./aws/**/*.yml
