name: Pull Request Checks


on:
  pull_request: {}


jobs:
  pr_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version-file: .python-version

      - uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Setup go-task/task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install Node dependencies
        run: npm install

      - name: PR Checks
        run: |
          task --output group \
               --output-group-begin "::group::{{.TASK}}{{if .NAME}}:{{.NAME}}{{end}}" \
               --output-group-end "::endgroup::" \
               ci
