name: Pull Request Checks

on:
  pull_request: {}

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Setup go-task/task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Install Python dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: PR Checks
        run: task -t Taskfile.github.yaml gh:ci
